server:
  port: 8888
spring:
  application:
    name: ConfigServer
  cloud:
    config:
      server:
        git:
          # 配置git仓库地址
          uri: https://github.com/ffch/ConfigServerTest.git
          # 公开仓库可以不填写用户名和密码
          username:
          password:
          #支持带{application}和{profile}（{label}如果需要）占位符的搜索路径
          search-paths: '{application}'
      # 配置仓库的分支,可不配
      label: master
